prometheus:
  server.route:
    enabled: true
    parentRefs:
    - name: shared-gateway
      namespace: default
      sectionName: prometheus-https
    hostnames:
    - prometheus.local
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
