apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-60'
  name: keycloack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'oci://registry-1.docker.io/bitnamicharts/keycloak'
    path: .
    targetRevision: 25.2.0
    helm:
      valuesObject:
        image:
          repository: bitnamilegacy/keycloak
        postgresql:
          image:
            repository: bitnamilegacy/postgresql
        extraEnvVars:
          - name: KC_PROXY_HEADERS
            value: 'xforwarded'
  - repoURL: 'https://github.com/evsor/k3d-dev-cluster.git'
    targetRevision: main
    path: cluster/components/keycloack
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true