apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-70'
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.17.9
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true