apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-80'
  name: shared-lb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/evsor/k3d-dev-cluster.git'
    targetRevision: main
    path: cluster/components/shared-lb
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true